name: Update NextDNS Rewrites

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-rewrites:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Using the latest version

      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y jq dnsutils

      - name: Query IP addresses and update DNS rewrites
        env:
          NEXTDNS_PROFILE_ID: ${{ secrets.NEXTDNS_PROFILE_ID }}
          NEXTDNS_API_KEY: ${{ secrets.NEXTDNS_API_KEY }}
        run: |
          DOMAINS=("archive.today" "archive.ph" "archive.is")
          DNS_SERVER="1.1.1.1"

          update_dns_rewrite() {
              local domain=$1
              local ip_address=$2
              echo "Updating rewrite for ${domain} to ${ip_address}"

              # Fetch existing rewrites
              existing_rewrite=$(curl -s -X GET "https://api.nextdns.io/profiles/${NEXTDNS_PROFILE_ID}/rewrites" \
                -H "x-api-key: ${NEXTDNS_API_KEY}")

              # Check if the rewrite already exists
              rewrite_entry=$(echo "$existing_rewrite" | jq -r ".data[] | select(.name == \"${domain}\")")
              rewrite_id=$(echo "$rewrite_entry" | jq -r ".id")

              echo "Rewrite ID for ${domain}: ${rewrite_id}"

              if [[ -n "$rewrite_id" && "$rewrite_id" != "null" ]]; then
                  # Show the exact curl command
                  echo "Executing PUT request:"
                  echo "curl -X PUT \"https://api.nextdns.io/profiles/${NEXTDNS_PROFILE_ID}/rewrites/${rewrite_id}\" \
                    -H \"x-api-key: ${NEXTDNS_API_KEY}\" \
                    -H \"Content-Type: application/json\" \
                    -d '{\"name\":\"${domain}\",\"content\":\"${ip_address}\"}'"

                  # Update the existing rewrite
                  response=$(curl -s -X PUT "https://api.nextdns.io/profiles/${NEXTDNS_PROFILE_ID}/rewrites/${rewrite_id}" \
                    -H "x-api-key: ${NEXTDNS_API_KEY}" \
                    -H "Content-Type: application/json" \
                    -d "{\"name\":\"${domain}\",\"content\":\"${ip_address}\"}")

                  echo "$response"
                  echo "Attempted to update existing rewrite for ${domain}"
              else
                  # Show the exact curl command
                  echo "Executing POST request:"
                  echo "curl -X POST \"https://api.nextdns.io/profiles/${NEXTDNS_PROFILE_ID}/rewrites\" \
                    -H \"x-api-key: ${NEXTDNS_API_KEY}\" \
                    -H \"Content-Type: application/json\" \
                    -d '{\"name\":\"${domain}\",\"content\":\"${ip_address}\"}'"

                  # Create a new rewrite
                  response=$(curl -s -X POST "https://api.nextdns.io/profiles/${NEXTDNS_PROFILE_ID}/rewrites" \
                    -H "x-api-key: ${NEXTDNS_API_KEY}" \
                    -H "Content-Type: application/json" \
                    -d "{\"name\":\"${domain}\",\"content\":\"${ip_address}\"}")

                  echo "$response"
                  echo "Created new rewrite for ${domain}"
              fi
          }

          # Query DNS server and update rewrites
          for domain in "${DOMAINS[@]}"; do
              ip_address=$(dig +short "${domain}" @"${DNS_SERVER}" | head -n 1)
              
              if [[ -n "$ip_address" ]]; then
                  echo "Domain: ${domain}, IP: ${ip_address}"
                  update_dns_rewrite "${domain}" "${ip_address}"
              else
                  echo "No IP address found for ${domain} on ${DNS_SERVER}"
              fi
          done
